### ISSUE TITLE
TypeError: api.getRealmInvite is not a function

### ISSUE THREAD

**Issue by PointNetwork341** [PrismarineJS/prismarine-realms#20]
This is my code:
const authflow = new Authflow()
const api = RealmAPI.from(authflow, 'bedrock')
const realm = await api.getRealm('6435795')
const code = await api.getRealmInvite('6435795')

**Comment by extremeheat** [comment]
Need a release, feel free to make a PR

**Comment by extremeheat** [comment]
Should be fixed now, run npm update
